name: Build and Release Telegram Bot API Binary

on:
  schedule:
    - cron: '0 0 * * *' # Run at 00:00 UTC daily
  workflow_dispatch: # Allow manual trigger

jobs:
  check-upstream:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check_commit.outputs.should_build }}
      commit_sha: ${{ steps.check_commit.outputs.commit_sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for upstream updates
        id: check_commit
        run: |
          # Fetch the latest commit from tdlib/telegram-bot-api
          UPSTREAM_COMMIT=$(curl -s https://api.github.com/repos/tdlib/telegram-bot-api/commits/master | jq -r .sha)
          echo "Latest upstream commit: $UPSTREAM_COMMIT"

          # Check if last-built-commit.txt exists and read it
          LAST_COMMIT="none"
          if [ -f "last-built-commit.txt" ]; then
            LAST_COMMIT=$(cat last-built-commit.txt)
            echo "Last built commit: $LAST_COMMIT"
          else
            echo "No previous commit file found. Treating as first build."
          fi

          # Compare commits
          if [ "$UPSTREAM_COMMIT" != "$LAST_COMMIT" ]; then
            echo "New commit detected. Proceeding with build."
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "commit_sha=$UPSTREAM_COMMIT" >> $GITHUB_OUTPUT
          else
            echo "No new commits. Skipping build."
            echo "should_build=false" >> $GITHUB_OUTPUT
            echo "commit_sha=$UPSTREAM_COMMIT" >> $GITHUB_OUTPUT
          fi

  build-and-release:
    needs: check-upstream
    if: needs.check-upstream.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Increased timeout for build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build telegram-bot-api binary
        run: |
          docker build -t telegram-bot-api-builder \
            --build-arg TELEGRAM_API_REF=${{ needs.check-upstream.outputs.commit_sha }} \
            -f Dockerfile .
          docker create --name temp-container telegram-bot-api-builder
          docker cp temp-container:/telegram-bot-api/bin/telegram-bot-api ./telegram-bot-api
          docker rm temp-container

      - name: Verify binary
        run: |
          file telegram-bot-api
          # Expected: ELF 64-bit LSB executable, x86_64, ... statically linked

      - name: Save current commit
        run: |
          echo "${{ needs.check-upstream.outputs.commit_sha }}" > last-built-commit.txt
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add last-built-commit.txt
          git commit -m "Update last-built-commit.txt with commit ${{ needs.check-upstream.outputs.commit_sha }}"
          git push

      - name: Generate tag name
        id: generate_tag
        run: echo "TAG_NAME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Create or update release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.generate_tag.outputs.TAG_NAME }}
          name: Release ${{ steps.generate_tag.outputs.TAG_NAME }}
          body: |
            Statically linked telegram-bot-api binary for x86_64 Linux.
            Built from upstream commit: ${{ needs.check-upstream.outputs.commit_sha }}
            Compatible with Linux kernels ≥3.2.0.
          files: telegram-bot-api
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify on success
        if: success()
        run: |
          echo "Successfully built and released telegram-bot-api binary (tag: ${{ steps.generate_tag.outputs.TAG_NAME }}) for commit ${{ needs.check-upstream.outputs.commit_sha }}"
