name: Build and Release Telegram Bot API Binary

on:
  schedule:
    - cron: '0 0 * * *' # Run at 00:00 UTC daily
  workflow_dispatch: # Allow manual trigger
  # repository_dispatch removed as we build daily regardless

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Increased timeout for build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest upstream commit SHA
        id: get_commit
        # Run always for schedule or manual trigger
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          UPSTREAM_COMMIT=$(curl -s https://api.github.com/repos/tdlib/telegram-bot-api/commits/master | jq -r .sha)
          echo "Latest upstream commit: $UPSTREAM_COMMIT"
          echo "commit_sha=$UPSTREAM_COMMIT" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        # Run always for schedule or manual trigger
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: docker/setup-buildx-action@v3

      - name: Build telegram-bot-api binary
        # Run always for schedule or manual trigger
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          docker build -t telegram-bot-api-builder \
            --build-arg TELEGRAM_API_REF=${{ steps.get_commit.outputs.commit_sha || 'master' }} \
            -f Dockerfile .
          docker create --name temp-container telegram-bot-api-builder
          docker cp temp-container:/telegram-bot-api/bin/telegram-bot-api ./telegram-bot-api
          docker rm temp-container

      - name: Verify binary
        # Run always for schedule or manual trigger
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          file telegram-bot-api
          # Expected: ELF 64-bit LSB executable, x86_64, ... statically linked

      - name: Generate tag name
        # Run always for schedule or manual trigger
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        id: generate_tag
        run: echo "TAG_NAME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Create or update release
        # Run always for schedule or manual trigger
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.generate_tag.outputs.TAG_NAME }}
          name: Release ${{ steps.generate_tag.outputs.TAG_NAME }}
          body: |
            Statically linked telegram-bot-api binary for x86_64 Linux.
            Built from upstream commit: ${{ steps.get_commit.outputs.commit_sha || 'master' }}
            Compatible with Linux kernels ≥3.2.0.
          files: telegram-bot-api
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify on success
        # Run always on success for schedule or manual trigger
        if: success() && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
        run: |
          echo "Successfully built and released telegram-bot-api binary (tag: ${{ steps.generate_tag.outputs.TAG_NAME }}) for commit ${{ steps.get_commit.outputs.commit_sha || 'master' }}"